//
// Generated file, do not edit! Created by nedtool 4.6 from satFrameFwd.msg.
//

#ifndef _SATFRAMEFWD_M_H_
#define _SATFRAMEFWD_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>satFrameFwd.msg:17</tt> by nedtool.
 * <pre>
 * packet satFrameFwd
 * {
 *     int destL2Address;
 *     bool hasPayload;
 * }
 * </pre>
 */
class satFrameFwd : public ::cPacket
{
  protected:
    int destL2Address_var;
    bool hasPayload_var;

  private:
    void copy(const satFrameFwd& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const satFrameFwd&);

  public:
    satFrameFwd(const char *name=NULL, int kind=0);
    satFrameFwd(const satFrameFwd& other);
    virtual ~satFrameFwd();
    satFrameFwd& operator=(const satFrameFwd& other);
    virtual satFrameFwd *dup() const {return new satFrameFwd(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getDestL2Address() const;
    virtual void setDestL2Address(int destL2Address);
    virtual bool getHasPayload() const;
    virtual void setHasPayload(bool hasPayload);
};

inline void doPacking(cCommBuffer *b, satFrameFwd& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, satFrameFwd& obj) {obj.parsimUnpack(b);}


#endif // ifndef _SATFRAMEFWD_M_H_

